<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Bits.OrderManagement.Domain.Aggregates</AssemblyName>
    <RootNamespace>Bits.OrderManagement.Domain.Aggregates</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Platform.Infrastructure.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Common\Common.csproj" />
    <ProjectReference Include="..\..\Shared\SharedDto\SharedDto.csproj" />
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\Events\Events.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\ValueObjects\ValueObjects.csproj" />
  </ItemGroup>

</Project>
