<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Bits.OrderManagement.Read.EventHandlers</AssemblyName>
    <RootNamespace>Bits.OrderManagement.Read.EventHandlers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Platform.Infrastructure.Core" />
    <PackageReference Include="Platform.Infrastructure.Repository.MongoDb" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Common\Common.csproj" />
    <ProjectReference Include="..\..\Domain\Events\Events.csproj" />
    <ProjectReference Include="..\ViewModels\ViewModels.csproj" />
  </ItemGroup>

</Project>
