<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Bits.OrderManagement.Read.QueryHandlers</AssemblyName>
    <RootNamespace>Bits.OrderManagement.Read.QueryHandlers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Platform.Infrastructure.Core" />
    <PackageReference Include="Platform.Infrastructure.Repository.MongoDb" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Common\Common.csproj" />
    <ProjectReference Include="..\ViewModels\ViewModels.csproj" />
  </ItemGroup>

</Project>
