<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Bits.OrderManagement.Read.ViewModels</AssemblyName>
    <RootNamespace>Bits.OrderManagement.Read.ViewModels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Platform.Infrastructure.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Common\Common.csproj" />
    <ProjectReference Include="..\..\Shared\SharedDto\SharedDto.csproj" />
  </ItemGroup>

</Project>
