<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Domain\Aggregates\Aggregates.csproj" />
    <ProjectReference Include="..\..\src\Domain\DomainServices\DomainServices.csproj" />
    <ProjectReference Include="..\..\src\Domain\Events\Events.csproj" />
    <ProjectReference Include="..\..\src\Domain\Models\Models.csproj" />
    <ProjectReference Include="..\..\src\Shared\Common\Common.csproj" />
  </ItemGroup>

</Project>
