<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Bits.OrderManagement.Shared.SharedDto</AssemblyName>
    <RootNamespace>Bits.OrderManagement.Shared.SharedDto</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
